version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: flower_shop_user
      POSTGRES_PASSWORD: flower_shop_password
      POSTGRES_DB: flower_shop_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
